require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/*"

Lint/MissingSuper:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false