version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: issue_d
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  db:
    image: postgres:13.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: issue_d
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
